version: '3'
services:
  snippet-box:
    image: pawelmalak/snippet-box
    container_name: snippet-box
    volumes:
      - /portainer/Files/AppData/Config/snippetbox/data:/app/data
    ports:
      - 5000:5000
    restart: unless-stopped
