FROM node:latest as base
WORKDIR /usr/src/app
RUN npm install -g bun


FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json /temp/dev/
RUN cd /temp/dev && bun install


FROM base AS build
COPY --from=install /temp/dev/node_modules node_modules
COPY . .
RUN bun run build

FROM alpine:latest
COPY --from=build /usr/src/app/.output/ ./.output/
RUN apk add --no-cache bash curl git git-lfs openssh-client tar tini
RUN curl -fsSL https://bun.sh/install | bash

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["tail", "-f", "/dev/null"]


