# syntax = docker/dockerfile:1

ARG NODE_VERSION=18.14.2

FROM node:${NODE_VERSION}-slim as base
RUN npm install -g bun
ENV NODE_ENV=development

WORKDIR /src

# Build
FROM base as build

COPY --link package.json bun.lockb ./
RUN bun install

# Run
FROM base

COPY --from=build /src/node_modules /src/node_modules

CMD [ "sh", "-c", "bun run dev"]

