version: '3'

services:
  # dockerproxy:
  #   environment:
  #     CONTAINERS: 1
  #   image: tecnativa/docker-socket-proxy
  #   networks:
  #     - traefik
  #   ports:
  #     - 2375
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  proxy:
    image: 'traefik:v2.10'
    container_name: le-ploy-proxy
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - '--entrypoints.web.address=:80'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - le-ploy

  core:
    image: 'ghcr.io/daniel-le97/leploy:latest'
    container_name: le-ploy-core
    # environment:
    #   - NUXT_GITHUB_CLIENT_ID=${NUXT_GITHUB_CLIENT_ID:-b0b0b0b0b0b0b0b0b0b0}
    #   - NUXT_GITHUB_CLIENT_SECRET=${NUXT_GITHUB_CLIENT_SECRET:-b12312qwdaSDasd1123}
    #   - NUXT_AUTH_JS_SECRET=${NUXT_GITHUB_CLIENT_SECRET:-"b12312qwdaSDasd1123"}
    #   - NUXT_PUBLIC_AUTH_JS_BASE_URL="http://localhost:3000"
    depends_on:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.bun.rule=Host(`le-ploy.localhost`)
      - traefik.http.routers.bun.entrypoints=web
      - traefik.http.services.bun.loadbalancer.server.port=3000
      - traefik.http.services.bun.loadbalancer.server.scheme=http
    ports:
      - '3000:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - le-ploy

networks:
  le-ploy:
    driver: bridge
