version: '3.7'
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 68:68/tcp
      - 68:68/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /portainer/Files/AppData/Config/adguardhome/workdir:/opt/adguardhome/work
      - /portainer/Files/AppData/Config/adguardhome/confdir:/opt/adguardhome/conf
    restart: unless-stopped
