version: '2.1'
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
    volumes:
      - /portainer/Files/AppData/Config/bazarr/config:/config
      - /portainer/Movies:/movies # optional
      - /portainer/TV:/tv # optional
    ports:
      - 6767:6767
    restart: unless-stopped
