version: '3.6'
services:
  broadlinkmanager:
    image: techblog/broadlinkmanager
    network_mode: host
    container_name: broadlinkmanager
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/broadlinkmanager:/opt/broadlinkmanager/data
