version: '3.9'
services:
  freescout-db:
    image: mariadb
    container_name: Freescout-DB
    hostname: freescout-db
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: [CMD-SHELL, 'mysqladmin ping -P 3306 -prootpass | grep ''mysqld is alive'' || exit 1']
    volumes:
      - /portainer/Files/AppData/Config/freescout/db:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: freescoutuser
      MYSQL_PASSWORD: freescoutpass
      MYSQL_DATABASE: freescout
    restart: on-failure:5

  freescout:
    image: tiredofit/freescout:latest
    container_name: Freescout
    hostname: freescout
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: curl -f http://localhost:80/ || exit 1
    ports:
      - 5135:80
    volumes:
      - /portainer/Files/AppData/Config/freescout/data:/data:rw
      - /portainer/Files/AppData/Config/freescout/logs/:/www/logs:rw
    environment:
      ADMIN_EMAIL: yourownemail
      ADMIN_PASS: mariushosting
      SITE_URL: https://freescout.yourdomain.com
      ENABLE_SSL_PROXY: true
      DB_HOST: freescout-db
      DB_NAME: freescout
      DB_USER: freescoutuser
      DB_PASS: freescoutpass
    restart: on-failure:5
    depends_on:
      freescout-db:
        condition: service_healthy
