---
version: '3'
services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Athens
    volumes:
      - /portainer/Files/AppData/Config/Grocy:/config
    ports:
      - 9283:80
    restart: unless-stopped
