version: '3'
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Athens
    ports:
      - 5055:5055
    volumes:
      - /portainer/Files/AppData/Config/jellyseer:/app/config
    restart: unless-stopped
