version: '3.9'
services:
  kavita:
    image: kizaing/kavita:latest
    volumes:
      - ./manga:/manga
      - /portainer/Books:/books
      - /portainer/Files/AppData/Kavita/Data:/kavita/config
    ports:
      - '5000:5000'
    restart: unless-stopped
