version: '3.8'

services:

  linkstack:
    hostname: linkstack
    image: 'linkstackorg/linkstack:latest'
    environment:
      TZ: Europe/Athens
      SERVER_ADMIN: admin@example.com
      HTTP_SERVER_NAME: example.com
      HTTPS_SERVER_NAME: example.com
      LOG_LEVEL: info
      PHP_MEMORY_LIMIT: 256M
      UPLOAD_MAX_FILESIZE: 8M
    volumes:
      - /portainer/Files/AppData/Config/linkstack/data:/htdocs'
    ports:
      - '8188:80'
      - '8190:443'
    restart: unless-stopped

volumes:
  linkstack_data:
