---
version: '3.7'
services:
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
      - BASE_URL=/ombi # optional
    volumes:
      - /portainer/Files/AppData/Config/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped
