version: '3'

networks:
  app-global:
    external: true
  mysql-internal:

services:
  openbudgeteer:
    image: axelander/openbudgeteer
    container_name: openbudgeteer
    ports:
      - 8081:80
    environment:
      - Connection:Server=openbudgeteer-mysql
      - Connection:Port=3306
      - Connection:Database=openbudgeteer
      - Connection:User=openbudgeteer
      - Connection:Password=openbudgeteer
      - AppSettings:Culture=en-US
    depends_on:
      - mysql
    networks:
      - app-global
      - mysql-internal

  mysql:
    image: mysql
    container_name: openbudgeteer-mysql
    environment:
      MYSQL_ROOT_PASSWORD: myRootPassword
    volumes:
      - /portainer/Files/AppData/Config/openbudgeteer/data:/var/lib/mysql
    networks:
      - mysql-internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: openbudgeteer-phpmyadmin
    links:
      - mysql:db
    ports:
      - 8080:80
    networks:
      - app-global
      - mysql-internal

volumes:
  data:
