version: '2'
services:
  #
  # one is a single-node Teleport cluster called "one" (runs all 3 roles: proxy, auth and node)
  #
  one:
    image: teleport:latest
    container_name: one
    command: ${CONTAINERHOME}/build/teleport start -d -c ${CONTAINERHOME}/docker/one.yaml
    mem_limit: 300m
    memswap_limit: 0
    ports:
      - '3080:3080'
      - '3023:3023'
      - '3025:3025'
    environment:
      DEBUG: 1
      CONTAINERHOME: /root/go/src/github.com/gravitational/teleport
    # env_file: ./teleportenv.file
    volumes:
      - /portainer/Files/AppData/teleport/one/data/one:/var/lib/teleport
      - /portainer/Files/AppData/Config/teleport/one:/root/go/src/github.com/gravitational/teleport
      - certs:/mnt/shared/certs
    networks:
      teleport:
        ipv4_address: 172.10.1.1
        aliases:
          - one-lb

  #
  # one-node is a single-node Teleport cluster called "one" (runs all 3 roles: proxy, auth and node)
  #
  one-node:
    image: teleport:latest
    container_name: one-node
    command: ${CONTAINERHOME}/build/teleport start -d -c ${CONTAINERHOME}/docker/one-node.yaml
    environment:
      DEBUG: 1
      CONTAINERHOME: /root/go/src/github.com/gravitational/teleport
    # env_file: ./teleportenv.file
    mem_limit: 300m
    volumes:
      - /portainer/Files/AppData/teleport/one-node/data/one-node:/var/lib/teleport
      - /portainer/Files/AppData/Config/teleport/one-node:/root/go/src/github.com/gravitational/teleport
    networks:
      teleport:
        ipv4_address: 172.10.1.20

  #
  # one-sshd is a single-node Teleport cluster called "one" (runs all 3 roles: proxy, auth and node)
  #
  one-sshd:
    image: teleport:latest
    container_name: one-sshd
    command: /usr/bin/start-sshd.sh
    environment:
      DEBUG: 1
      CONTAINERHOME: /root/go/src/github.com/gravitational/teleport
    # env_file: ./teleportenv.file
    mem_limit: 300m
    volumes:
      - /portainer/Files/AppData/teleport/one-sshd/pam.d/ssh:/etc/pam.d/ssh
      - /portainer/Files/AppData/Config/teleport/one-sshd:/etc/ssh/sshd_config
      - certs:/mnt/shared/certs
    networks:
      teleport:
        ipv4_address: 172.10.1.21

  #
  # one-proxy is a second xproxy of the first cluster
  #
  one-proxy:
    image: teleport:latest
    container_name: one-proxy
    command: ${CONTAINERHOME}/build/teleport start -d -c ${CONTAINERHOME}/docker/one-proxy.yaml
    mem_limit: 300m
    ports:
      - '4080:3080'
      - '4023:3023'
    environment:
      DEBUG: 1
      CONTAINERHOME: /root/go/src/github.com/gravitational/teleport
    # env_file: ./teleportenv.file
    volumes:
      - /portainer/Files/AppData/teleport/one-proxy:/var/lib/teleport
      - /portainer/Files/AppData/Config/teleport/one-proxy:/root/go/src/github.com/gravitational/teleport
    networks:
      teleport:
        ipv4_address: 172.10.1.10
        aliases:
          - one-lb

  #
  # two-auth is a auth server of the second cluster
  #
  two-auth:
    mem_limit: 300m
    image: teleport:latest
    container_name: two-auth
    command: ${CONTAINERHOME}/build/teleport start -d -c ${CONTAINERHOME}/docker/two-auth.yaml --insecure
    environment:
      DEBUG: 1
      CONTAINERHOME: /root/go/src/github.com/gravitational/teleport
    # env_file: ./teleportenv.file
    volumes:
      - /portainer/Files/AppData/teleport/two/auth:/var/lib/teleport
      - /portainer/Files/AppData/Config/teleport/two:/root/go/src/github.com/gravitational/teleport
    networks:
      teleport:
        ipv4_address: 172.10.1.2

  #
  # two-proxy is a proxy service for the second cluster
  #
  two-proxy:
    mem_limit: 300m
    image: teleport:latest
    container_name: two-proxy
    command: ${CONTAINERHOME}/build/teleport start -d -c ${CONTAINERHOME}/docker/two-proxy.yaml
    environment:
      DEBUG: 1
      CONTAINERHOME: /root/go/src/github.com/gravitational/teleport
    # env_file: ./teleportenv.file
    ports:
      - '5080:5080'
      - '5023:5023'
    volumes:
      - /portainer/Files/AppData/teleport/two-proxy/data:/var/lib/teleport
      - /portainer/Files/AppData/Config/teleport/two-proxy:/root/go/src/github.com/gravitational/teleport
    networks:
      teleport:
        ipv4_address: 172.10.1.3

  #
  # two-node is a node service for the second cluster
  #
  two-node:
    mem_limit: 300m
    image: teleport:latest
    container_name: two-node
    command: ${CONTAINERHOME}/build/teleport start -d -c ${CONTAINERHOME}/docker/two-node.yaml
    environment:
      DEBUG: 1
      CONTAINERHOME: /root/go/src/github.com/gravitational/teleport
    # env_file: ./teleportenv.file
    volumes:
      - /portainer/Files/AppData/teleport/two-node/data:/var/lib/teleport
      - /portainer/Files/AppData/Config/teleport/two-node:/root/go/src/github.com/gravitational/teleport
    networks:
      teleport:
        ipv4_address: 172.10.1.4

networks:
  teleport:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.1.0/16
          ip_range: 172.10.1.0/24
          gateway: 172.10.1.254

volumes:
  certs:
