version: '3.7'
services:
  traggo:
    image: traggo/server:latest
    ports:
      - 3030:3030
    environment:
      TRAGGO_DEFAULT_USER_NAME: admin
      TRAGGO_DEFAULT_USER_PASS: mynewpassword
    volumes:
      - /portainer/Files/AppData/Config/traggo/data:/opt/traggo/data
