# Simple docker-compose.yml
# You can change your port or volume location
version: '2.1'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /portainer/Files/AppData/Config/uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001 # <Host Port>:<Container Port>
    restart: always
