services:
  wger-web:
    image: wger/server:latest
    container_name: wger_server
    depends_on:
      wger-db:
        condition: service_healthy
      wger-cache:
        condition: service_healthy
    environment:
      - SECRET_KEY=wger-docker-supersecret-key-1234567890!@#$%^&*(-_)
      - SIGNING_KEY=wger-docker-secret-jwtkey-1234567890!@#$%^&*(-_=+
      - FROM_EMAIL=info@example.com
      - TIME_ZONE=Europe/Athens
      # Application
      - ALLOW_REGISTRATION=True
      - ALLOW_GUEST_USERS=True
      - ALLOW_UPLOAD_VIDEOS=Tru
      # Users won't be able to contribute to exercises if their account age is
      # lower than this amount in days.
      - MIN_ACCOUNT_AGE_TO_TRUST=21
      # Note that setting these to true will always perform a sync during startup,
      # even if the data is already current and will take some time. Usually you don't
      # need to perform these steps so often and a manual trigger (see README) is
      # usually enough.
      - SYNC_EXERCISES_ON_STARTUP=False
      - DOWNLOAD_EXERCISE_IMAGES_ON_STARTUP=False
      # Database
      - DJANGO_DB_ENGINE=django.db.backends.postgresql
      - DJANGO_DB_DATABASE=wger
      - DJANGO_DB_USER=wger
      - DJANGO_DB_PASSWORD=wger
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      # Perform any new database migrations on startup
      - DJANGO_PERFORM_MIGRATIONS=True
      # Cache
      - DJANGO_CACHE_BACKEND=django_redis.cache.RedisCache
      - DJANGO_CACHE_LOCATION=redis://cache:6379/1
      # 60*60*24*15, 15 Days
      - DJANGO_CACHE_TIMEOUT=12
      - DJANGO_CACHE_CLIENT_CLASS=django_redis.client.DefaultClient

      # Brute force login attacks
      # https://django-axes.readthedocs.io/en/latest/index.html
      - AXES_ENABLED=True
      - AXES_FAILURE_LIMIT=10
      # in minutes
      - AXES_COOLOFF_TIME=30
      - AXES_HANDLER=axes.handlers.cache.AxesCacheHandler
      #
      # Others
      - DJANGO_DEBUG=False
      - WGER_USE_GUNICORN=True
      - EXERCISE_CACHE_TTL=10
      - SITE_URL=http://localhost
      #
      # JWT auth
      # The lifetime duration of the access token, in minutes
      - ACCESS_TOKEN_LIFETIME=10
      # The lifetime duration of the refresh token, in hours
      - REFRESH_TOKEN_LIFETIME=24
      #
      # Other possible settings

      # RECAPTCHA_PUBLIC_KEY
      # RECAPTCHA_PRIVATE_KEY
      # NOCAPTCHA
      # https://docs.djangoproject.com/en/4.1/topics/email/#smtp-backend
      # ENABLE_EMAIL
      # EMAIL_HOST
      # EMAIL_PORT
      # EMAIL_HOST_USER
      # EMAIL_HOST_PASSWORD
      # EMAIL_USE_TLS
      # EMAIL_USE_SSL
      # DJANGO_MEDIA_ROOT
      # DJANGO_STATIC_ROOT
    volumes:
      - /portainer/Files/AppData/Config/wger/static:/home/wger/static
      - /portainer/Files/AppData/Config/wger/media:/home/wger/media
      # For development, mount your local git checkout
      # - type: bind
      #  source: /path/to/wger/sourcecode
      #  target: /home/wger/src/
    ports:
      - '8000'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  wger-nginx:
    image: nginx:stable
    container_name: wger_nginx
    depends_on:
      - wger-web
    volumes:
      - /portainer/Files/AppData/Config/wger/nginx.conf:/etc/nginx/conf.d/default.conf
      - /portainer/Files/AppData/Config/wger/static:/wger/static:ro
      - /portainer/Files/AppData/Config/wger/media:/wger/media:ro
    ports:
      - '680:80'
    healthcheck:
      test: service nginx status
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  wger-db:
    image: postgres:12-alpine
    container_name: wger_db
    environment:
      - POSTGRES_USER=wger
      - POSTGRES_PASSWORD=wger
      - POSTGRES_DB=wger
    volumes:
      - /portainer/Files/AppData/Config/wger/postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432
    healthcheck:
      test: pg_isready -U wger
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  wger-cache:
    image: redis
    container_name: wger_cache
    expose:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-data:
  static:
  media:

networks:
  default:
    name: wger_network
